# makefile for ~/.config/pentadactyl by luc
# vim: foldmethod=marker

include generic.mk

CONFIGS = \
	  $(HOME)$(SEP).$(SEP).pentadactyl               \
	  $(HOME)$(SEP)pentadactylrc$(SEP).pentadactylrc \
