# makefile to create and remove links from $HOME to the dotfile directory
# vim: foldmethod=marker

# include the generic makefile
include generic.mk

# variables {{{1
# file lists {{{2
# this is ugly because I need pairs.
CONFIGS = \
          $(HOME)$(SEP)abcde.conf$(SEP).abcde.conf          \
          $(HOME)$(SEP)mpd$(SEP).mpd                        \
          $(HOME)$(SEP)ncmpcpp$(SEP).ncmpcpp                \
	  $(HOME)/.config$(SEP)MusicBrainz$(SEP)MusicBrainz \
	  $(HOME)/.config$(SEP)easytag$(SEP)easytag         \
