# makefile for ~/.config/music by luc

# include the generic makefile
include generic.mk

CONFIGS = \
          abcde.conf$(SEP).abcde.conf \
          mpd$(SEP).mpd               \
          ncmpcpp$(SEP).ncmpcpp       \

OTHER = \
	$(HOME)/.config$(SEP)$(patsubst $(HOME)/.config/%,%,$(HOME)/$(DIR)/MusicBrainz)$(SEP)MusicBrainz \
	$(HOME)/.config$(SEP)$(patsubst $(HOME)/.config/%,%,$(HOME)/$(DIR)/easytag)$(SEP)easytag         \
