# makefile for ~/.config/mail by luc

include generic.mk

CONFIGS = \
	  $(HOME)$(SEP)mailcheckrc$(SEP).mailcheckrc \
	  $(HOME)$(SEP)mutt$(SEP).mutt               \
	  $(HOME)$(SEP)fetchmailrc$(SEP).fetchmailrc \

OTHER = $(HOME)/$(DIR)/mutt/profiles$(SEP)$(realpath $(HOME)/$(DIR)/../secure/mutt-profiles)$(SEP)all 
