# makefile for ~/.config/mail by luc

include generic.mk

CONFIGS = \
	  mailcheckrc$(SEP).mailcheckrc \
	  mutt$(SEP).mutt               \
	  fetchmailrc$(SEP).fetchmailrc \

OTHER = $(HOME)/$(DIR)/mutt/profiles$(SEP)$(realpath $(HOME)/$(DIR)/../secure/mutt-profiles)$(SEP)all 
